### PR TITLE
Added None in some flags to fix HasFlags method

### PR DESCRIPTION
**Pull request by joosthoi1**
Specifically `Linearstar.Windows.RawInput.Native.RawKeyboardFlags` and `Linearstar.Windows.RawInput.Native.RawMouseFlags`

### CODE REVIEW

**Review by mfakane — CHANGES_REQUESTED** [review]
`RawKeyboardFlags` is a enum representation for `RI_KEY_*`, and `RawMouseFlags` is for `MOUSE_MOVE_*`. (https://github.com/mfakane/rawinput-sharp/issues/9#issuecomment-830033763)
We can change the name, but not the value. So we need to do either of the following:

1. Change the name of the `Down` and `MoveRelative` to `None`, and leave the value same.
2. Use the enum to represent the flags in .NET's familiar way, and convert raw `usFlags` value to that enum values using property getter.

**Comment by joosthoi1** [comment]
For now I reverted my changes and renamed the first flag to None to avoid confusion. 

I also changed the name of LeftKey and RightKey to KeyE0 and KeyE1 seeing as they are supposed to be used as flags for if the scancode is preceded by E0 or E1 (https://www.win.tue.nl/~aeb/linux/kbd/scancodes-1.html)

**Review by mfakane — APPROVED** [review]
Looks good, thanks for your fixes!

**Comment by joosthoi1** [comment]
Sure, also, it might be worth copying the comments given on the pinvoke website (Included with their .net definitions of winuser.h funcitons and structs) for example with RawKeyboardFlags copying 
```cs
/// <summary>
/// Enumeration containing flags for raw keyboard input.
/// </summary>
```
from https://www.pinvoke.net/default.aspx/Enums/RawKeyboardFlags.html and possibly additional comments

**Pull request merged**
